language: python

sudo: false

# Travis whitelists the installable packages, additions can be requested
#   https://github.com/travis-ci/apt-package-whitelist
addons:
  apt:
    packages: &common_packages
      - gfortran
      - libatlas-dev
      - libatlas-base-dev
      - eatmydata

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 2.7
#  - 3.4
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
#  - 3.7-dev

install:
- uname -a
- free -m
- df -h
- ulimit -a
- mkdir builds
- pushd builds
# Build into own virtualenv
# We therefore control our own environment, avoid travis' numpy
#
- pip install -U virtualenv
- virtualenv --python=python venv
- source venv/bin/activate
- python -V
- pip install --upgrade pip setuptools
#- pip install nose pytz cython
- popd
#- pip install -U pip
- pip install .
- pip install python-coveralls

script:
- echo "Python version:"
- python --version
- coverage run -m unittest discover quantdsl.tests -v

after_success:
- coveralls
